apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: reachjalil/demo:app_1.0.1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker-auth
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-route
spec:
  hosts:
    - "cv.tldis.icu"
  gateways:
    - mforms-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: app-service
            port:
              number: 80
