apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: reachjalil/demo:server_1
          env:
            - name: NODE_ENV
              value: "production"
            - name: ENDPOINT
              value: "https://cv.tldis.icu"
            - name: SECRET
              value: "secret_here"
            - name: CONSUMER_SECRET
              value: "TODO"
          ports:
            - containerPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: server-route
spec:
  hosts:
    - "sv.tldis.icu"
  gateways:
    - demo-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: server-service
            port:
              number: 80
